language: php

php:
  - '7.2'

services:
  - mysql

before_install:
  - npm install -g yarn
  - chmod +x bin/console
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_student;'

install:
  - composer install
  - npm install
  - yarn build

script:
  -  SYMFONY_DEPRECATIONS_HELPER='/Doctrine\\Common\\ClassLoader is deprecated\./' ./vendor/bin/simple-phpunit